
module.exports = {
  EMPTY_LINE: 'EMPTY_LINE',
  INCREASE_NESTING: 'INCREASE_NESTING',
  DECREASE_NESTING: 'DECREASE_NESTING',
  END_LINE: 'END_LINE',
  VARIABLE: 'VARIABLE',
  VARIABLE_NAME: 'VARIABLE_NAME',
  VARIABLE_VALUE: 'VARIABLE_VALUE',
  INTEGER: 'INTEGER',
  FLOAT: 'FLOAT',
  STRING: 'STRING',
  INFINITY: 'INFINITY',
  BOOLEAN: 'BOOLEAN',
  OBJECT: 'OBJECT',
  OBJECT_FIELD_NAME: 'OBJECT_FIELD_NAME',
  OBJECT_FIELD_VALUE: 'OBJECT_FIELD_VALUE'
}